---
ip_spaces:
  - name: "datacenter-eu-central"
    comment: "Created by Ansible"
    state: absent
    tags: {}

  - name: "datacenter-eu-east"
    comment: "Created by Ansible"
    state: absent
    tags: {}
