---
- name: Verify Infoblox DDI Configuration
  hosts: infoblox_portal

  module_defaults:
    group/infoblox.universal_ddi.all:
      portal_url: "{{ infoblox_portal_url | default(omit) }}"
      api_key: "{{ infoblox_portal_api_key | default(omit) }}"

  roles:
    - infrastructure_verify
